//
//  TapSDKConstants.h
//  TapBootstrapSDK
//
//  Created by Bottle K on 2021/2/25.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXTERN int const ERROR_CODE_UNDEFINED;
FOUNDATION_EXTERN int const ERROR_CODE_UNINITIALIZED;

FOUNDATION_EXTERN int const ERROR_CODE_BIND_CANCEL;
FOUNDATION_EXTERN int const ERROR_CODE_BIND_ERROR;

FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_INVALID_LOGIN_STATE;
FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_USER_CENER_LOGOUT;
FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_GAME;
FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_KICKED;

NS_ASSUME_NONNULL_END
